"""empty message

Revision ID: 4274a63062dc
Revises: a72f28944867
Create Date: 2022-08-03 09:20:51.900416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4274a63062dc'
down_revision = 'a72f28944867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('tmp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'tmp')
    # ### end Alembic commands ###
