"""empty message

Revision ID: e7a9d90bcc48
Revises: 4274a63062dc
Create Date: 2022-08-03 09:21:35.352088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a9d90bcc48'
down_revision = '4274a63062dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'tmp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('tmp', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
