"""empty message

Revision ID: f6005749372e
Revises: a12c36a086d7
Create Date: 2022-07-31 20:22:45.277655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6005749372e'
down_revision = 'a12c36a086d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_artist', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_artist', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
